version: "3.8"

services:
  # API
  api:
    container_name: google_keep_clone_api
    build: ./api
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_SCHEMA: keep
    depends_on:
      - postgres
    networks:
      - keep

  # FRONT
  front:
    container_name: google_keep_clone_front
    build: ./front
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      BUSINESS_NAME: Google Keep Clone
      BUSINESS_DESCRIPTION: Clone da Aplicação Google Keep
      BUSINESS_URL: http://localhost:3000
      API_URL: http://localhost:8000
    depends_on:
      - api
    networks:
      - keep

  # DB
  postgres:
    container_name: google_keep_clone_db
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: keep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keep

networks:
  keep:
    driver: bridge

volumes:
  postgres_data:
